# Generated by Django 3.1.7 on 2022-03-28 21:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuser',
            name='activation_key',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 29, 21, 56, 37, 41095, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='shopuser',
            name='address',
            field=models.CharField(blank=True, max_length=256, verbose_name='Адрес доставки'),
        ),
        migrations.AddField(
            model_name='shopuser',
            name='phone',
            field=models.IntegerField(null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='age',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='возраст'),
        ),
    ]
