# Generated by Django 3.1.7 on 2021-06-19 20:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_auto_20210612_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 20, 20, 2, 17, 608922, tzinfo=utc)),
        ),
    ]
