# Generated by Django 3.1.7 on 2021-05-30 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='имя')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(blank=True, max_length=128, null=True, verbose_name='имя продукта')),
                ('name', models.CharField(max_length=128, verbose_name='имя продукта')),
                ('series', models.CharField(blank=True, max_length=64, null=True, verbose_name='серия')),
                ('type', models.CharField(blank=True, max_length=32, null=True, verbose_name='тип светильника')),
                ('type_2', models.CharField(blank=True, max_length=32, null=True, verbose_name='подтип')),
                ('material', models.CharField(blank=True, max_length=32, null=True, verbose_name='метериал')),
                ('color', models.CharField(blank=True, max_length=16, null=True, verbose_name='цвет')),
                ('price', models.PositiveIntegerField(null=True, verbose_name='цена')),
                ('lamps', models.PositiveIntegerField(default=1, null=True, verbose_name='количество ламп')),
                ('lamps_type', models.CharField(blank=True, max_length=16, null=True, verbose_name='цоколь')),
                ('power', models.CharField(max_length=16, null=True, verbose_name='мощность')),
                ('length', models.CharField(max_length=16, null=True, verbose_name='длина')),
                ('width', models.CharField(max_length=16, null=True, verbose_name='ширина')),
                ('height', models.CharField(max_length=16, null=True, verbose_name='высота')),
                ('diameter', models.CharField(max_length=16, null=True, verbose_name='диаметр')),
                ('size', models.CharField(blank=True, max_length=32, null=True, verbose_name='размер')),
                ('weight', models.CharField(blank=True, max_length=16, null=True, verbose_name='вес')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products_images')),
                ('short_desc', models.CharField(blank=True, max_length=60, verbose_name='краткое описание')),
                ('descriptions', models.CharField(blank=True, max_length=128, verbose_name='описание')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='количество на складе')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.productcategory')),
            ],
            options={
                'verbose_name': 'продукт',
                'verbose_name_plural': 'продукты',
            },
        ),
    ]
