# Generated by Django 3.1.7 on 2022-03-28 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_2',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='products_images', verbose_name='фото-2'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_3',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='products_images', verbose_name='фото-3'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_4',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='products_images', verbose_name='фото-4'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_5',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='products_images', verbose_name='фото-5'),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='цена cо скидкой'),
        ),
        migrations.AddField(
            model_name='product',
            name='style',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='стиль'),
        ),
        migrations.AlterField(
            model_name='product',
            name='article',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='артикул'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.productcategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='цвет'),
        ),
        migrations.AlterField(
            model_name='product',
            name='descriptions',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='diameter',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='диаметр'),
        ),
        migrations.AlterField(
            model_name='product',
            name='height',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='высота'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='products_images', verbose_name='фото'),
        ),
        migrations.AlterField(
            model_name='product',
            name='lamps',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='количество ламп'),
        ),
        migrations.AlterField(
            model_name='product',
            name='length',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='длина'),
        ),
        migrations.AlterField(
            model_name='product',
            name='material',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='метериал'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=128, null=True, verbose_name='имя продукта'),
        ),
        migrations.AlterField(
            model_name='product',
            name='power',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='мощность'),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_desc',
            field=models.CharField(blank=True, max_length=64, verbose_name='краткое описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='размер'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='тип светильника'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type_2',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='подтип'),
        ),
        migrations.AlterField(
            model_name='product',
            name='width',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='ширина'),
        ),
    ]
